name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:   
    - cron: '0 12 * * *'

jobs:
  build:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Use Node.js 21
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 21
        cache: 'npm'
    - run: npm install      
    - run: npm test
